services:
  - type: web
    name: internexis-official
    env: node
    region: oregon
    plan: free
    buildCommand: npm install && npm run build --prefix ../frontend
    startCommand: node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        value: mongodb+srv://internexis_user:internexis_user@cluster0.b9dwnfz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
      - key: MONGO_URI
        value: mongodb+srv://internexis_user:internexis_user@cluster0.b9dwnfz.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
    autoDeploy: true
